# Generated by Django 5.1.2 on 2024-10-11 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
        ('order_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_fname', models.CharField(max_length=50)),
                ('c_mname', models.CharField(blank=True, max_length=50)),
                ('c_lname', models.CharField(max_length=50)),
                ('c_phone_no', models.CharField(max_length=15)),
                ('c_email', models.EmailField(max_length=254)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='order_app.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='admin_app.admin')),
            ],
        ),
    ]
