# Generated by Django 5.1.2 on 2024-10-11 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='status',
            new_name='order_status',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
