# Generated by Django 5.1.2 on 2024-10-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_fname', models.CharField(max_length=50)),
                ('a_mname', models.CharField(blank=True, max_length=50)),
                ('a_lname', models.CharField(max_length=50)),
                ('a_email', models.EmailField(max_length=254)),
                ('a_phone_no', models.CharField(max_length=15)),
                ('user', models.CharField(max_length=50)),
                ('password', models.CharField(default='pbkdf2_sha256$870000$765lZ3oPxzPFIRaD1bAi7z$GNNEcxWo2EtBdpv6rb02zwU8mt4f4d4QANqiK7v+/H8=', max_length=50)),
            ],
        ),
    ]
