# Generated by Django 5.1.2 on 2024-10-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$euleBrfeAT0mgQta8E50WI$fvE5UHWcJy7sUwmRREXd9DjgodDb0ED0+Yh+A5TtjyU=', max_length=50),
        ),
    ]
