# Generated by Django 5.1.2 on 2024-10-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$KSxB7XFNm0J1haY016JVm9$26BasiMH0Kmxbhov4G8oOcZH49BF5xOTDRIj7Lx8ew8=', max_length=50),
        ),
    ]
