# Generated by Django 5.1.2 on 2024-10-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$ldBGCDE2jybc1Kf3iu3O4l$b2JsGfp8+nCFhho0YsBcgnyerQBqnqE6uD2oogSgfRg=', max_length=50),
        ),
    ]
