# Generated by Django 5.1.2 on 2024-10-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_alter_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$GnVxG4hSgZGjBHPpQmpPbz$5ob91AZoNMOzbjnEJyylcDHrN20B5/Zy3Bcc2jEHB+M=', max_length=50),
        ),
    ]
