# Generated by Django 5.1.2 on 2024-10-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_alter_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$SgwbMu1Ca5aqNCht2sqEwX$eXqOP09Visx1TzEjHHYzER9Z3v0kTxNthHz+2n+2EH0=', max_length=50),
        ),
    ]
