# Generated by Django 5.1.2 on 2024-10-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_alter_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$xoGBzhhHcavIYOCYKHKi1W$L+uzuY7a9BqOONL/mcquGijsL7llLXWNHNQgPbf4mGY=', max_length=50),
        ),
    ]
