# Generated by Django 5.1.2 on 2024-10-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_alter_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$LUiGzR8N5TOalkrIQJwEcw$wYQU5U5aRqFdRkMycAQyn3quHwHIxg0iKg4c6PwlCD8=', max_length=50),
        ),
    ]
