# Generated by Django 5.1.2 on 2024-10-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_alter_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$DdHWi8fzwqmLeU0TgIWIgR$0zLZQu3qrmKTjx3pi8lHDJ1l/MoPlmKmu0EFwPS8LtQ=', max_length=50),
        ),
    ]
