# Generated by Django 5.1.2 on 2024-10-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_alter_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$p8eeAHOdgChs5h89PRZr0Q$No4cDyvxajU6qx7rNe/s0rKKUMbYTg440b/70LJomCs=', max_length=50),
        ),
    ]
