# Generated by Django 5.1.2 on 2024-10-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_alter_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$s6kjM0iwW7n8ZGktMeQlJk$BsrXHfpcdV4Lr4j0jf94wYdrNJHCHqsQrI5su7IfWYw=', max_length=50),
        ),
    ]
