# Generated by Django 5.1.2 on 2024-10-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_alter_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$6aSlV39tGwZ0rFqAN8aodp$WaWIcd6PWuG1FccGYieiQsk4QC0t/w2o2Btey3A/dGg=', max_length=50),
        ),
    ]
