# Generated by Django 5.1.2 on 2024-10-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_alter_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$KH76uFCY5tJa9znqtrYRr0$/ihV8CXRyPo80lPRzcQs7PqCSd+iD+hqt7/xbvk1v1o=', max_length=50),
        ),
    ]
