# Generated by Django 5.1.2 on 2024-10-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0016_alter_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$AWCl8BvL6cUfdInUE0N5MU$9BgLM5mphEm/mXjhGwU/odb7aBnkk35J0TNNBdydQEs=', max_length=50),
        ),
    ]
