# Generated by Django 5.1.2 on 2024-10-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0017_alter_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$R3yb2Wx07MR9RuRMxDHYuF$jX8LJ/GPDheyqSaJ7cG56SBs+qJNe1w/12KgowxhoHw=', max_length=50),
        ),
    ]
