# Generated by Django 5.1.2 on 2024-10-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0018_alter_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$QvvQkvZpVI98SuzXlzCfn9$vhppggXayYSz7E1+pPeEvOm+YX3EiwnLwqxUr58V1ls=', max_length=50),
        ),
    ]
