# Generated by Django 5.1.2 on 2024-10-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0019_alter_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$6s2fuPpgly5o8gBjROUgAP$NtqXsXWMpgK8iZ/nYzMqrz6eo0qPxNijWgfjWYnl71A=', max_length=50),
        ),
    ]
